import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { useState } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { projectsApi } from "../../api/projectsApi";
import { ProjectWorkspace } from "./components/ProjectWorkspace";

vi.mock("../../api/projectsApi", () => ({
  projectsApi: {
    detail: vi.fn(),
    activity: vi.fn(),
    generateTasks: vi.fn(),
    generateDependencies: vi.fn(),
    generateGates: vi.fn(),
    dependencies: vi.fn(),
    externalGates: vi.fn(),
    templateReviewTasks: vi.fn(),
    templateReviewSummary: vi.fn(),
    setStatus: vi.fn(),
    setMembership: vi.fn(),
    remove: vi.fn(),
  },
}));

function draft(overrides = {}) {
  return {
    id: "project-1", code: "PRJ-001", name: "Khar Commercial Project", client_name: "Castrol India",
    site_address: "Khar, Mumbai", description: null, start_date: "2026-08-01",
    target_handover_date: "2026-09-14", template_version_id: "version-1", status: "draft",
    memberships: [], membership_history: [],
    setup: {
      has_project_manager: true, has_site_supervisor: true, has_template: true,
      has_target_handover_date: true, activation_ready: true,
    },
    ...overrides,
  };
}

const templates = [{
  version_id: "version-1", version_no: 1, template_code: "WORKVED-45",
  template_name: "Workved 45-Day Permanent Task Template", duration_days: 45,
  status: "published", is_current_published: true,
}];

// Creation now audits the snapshot it generated, so a project made through the
// portal always arrives with this on its trail.
const createdWithSnapshot = [{
  id: "audit-0", action: "PROJECT_CREATED", after: { generated_task_count: 99, generated_dependency_count: 38, generated_gate_count: 32 },
  occurred_at: "2026-07-29T09:00:00Z", actor_name: "Admin", reason: "Created",
}];

const generatedManually = [{
  id: "audit-1", action: "PROJECT_TASKS_GENERATED", after: { generated_task_count: 99 },
  occurred_at: "2026-07-29T10:00:00Z", actor_name: "Admin", reason: "Generated",
}];

function Harness({ role = "admin" }) {
  const [pane, setPane] = useState("overview");
  return <ProjectWorkspace
    projectId="project-1"
    references={{ project_managers: [], supervisors: [], internal_employees: [] }}
    templates={templates}
    user={{ id: "admin-1", role }}
    pane={pane}
    onPaneChange={setPane}
    onEdit={vi.fn()}
    onChanged={vi.fn().mockResolvedValue(undefined)}
    onDeleted={vi.fn()}
  />;
}

beforeEach(() => {
  vi.clearAllMocks();
  projectsApi.detail.mockResolvedValue(draft());
  projectsApi.activity.mockResolvedValue(createdWithSnapshot);
  projectsApi.dependencies.mockResolvedValue({ total: 38, items: [] });
  projectsApi.externalGates.mockResolvedValue({ total: 32, items: [] });
  projectsApi.templateReviewTasks.mockResolvedValue({ items: [], pagination: { page: 1, page_size: 100, total: 0, total_pages: 0 } });
  projectsApi.templateReviewSummary.mockResolvedValue({ project_id: "project-1", total: 99, included: 99, excluded: 0, pending_review: 99, decided: 0, mandatory: 98, conditional: 1 });
});

describe("Draft project setup", () => {
  it("asks for nothing when creation already prepared the schedule", async () => {
    render(<Harness/>);
    expect(await screen.findByText("Ready to activate")).toBeInTheDocument();
    expect(screen.getByText("99 tasks prepared")).toBeInTheDocument();
    // Dependency and gate counts are fetched separately from the detail call.
    expect(await screen.findByText("38 dependencies, 32 approval gates")).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /^generate tasks$/i })).not.toBeInTheDocument();
    expect(projectsApi.generateTasks).not.toHaveBeenCalled();
  });

  it("names the tab Task Review rather than Template Review", async () => {
    render(<Harness/>);
    await screen.findByText("Ready to activate");
    expect(screen.getByRole("button", { name: /task review/i })).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /template review/i })).not.toBeInTheDocument();
  });

  it("blocks the activation hand-off until the project is ready", async () => {
    projectsApi.detail.mockResolvedValue(draft({
      target_handover_date: null,
      setup: { has_project_manager: true, has_site_supervisor: true, has_template: true, has_target_handover_date: false, activation_ready: false },
    }));
    render(<Harness/>);
    expect(await screen.findByText("Setup incomplete")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /activation blocked/i })).toBeDisabled();
  });

  it("still recognises a snapshot generated by the old manual step", async () => {
    projectsApi.activity.mockResolvedValue(generatedManually);
    render(<Harness/>);
    expect(await screen.findByText("99 tasks prepared")).toBeInTheDocument();
  });

  describe("drafts created before setup became automatic", () => {
    beforeEach(() => {
      projectsApi.activity.mockResolvedValue([]);
      projectsApi.dependencies.mockResolvedValue({ total: 0, items: [] });
      projectsApi.externalGates.mockResolvedValue({ total: 0, items: [] });
    });

    it("offers a confirmed fallback and generates once", async () => {
      projectsApi.generateTasks.mockResolvedValue({ generated_task_count: 99, no_op: false });
      projectsApi.activity.mockResolvedValueOnce([]).mockResolvedValue(generatedManually);

      render(<Harness/>);
      expect(await screen.findByText("This draft has no task schedule")).toBeInTheDocument();
      const generate = screen.getByRole("button", { name: /generate tasks/i });
      expect(generate).toBeDisabled();
      fireEvent.click(screen.getByRole("checkbox"));
      fireEvent.click(generate);
      fireEvent.click(generate);

      await waitFor(() => expect(projectsApi.generateTasks).toHaveBeenCalledTimes(1));
      expect(await screen.findByText("99 tasks prepared")).toBeInTheDocument();
    });

    it("shows an error and allows a controlled retry", async () => {
      projectsApi.generateTasks
        .mockRejectedValueOnce(new Error("Generation transaction rolled back."))
        .mockResolvedValueOnce({ generated_task_count: 99, no_op: false });
      projectsApi.activity.mockResolvedValueOnce([]).mockResolvedValue(generatedManually);

      render(<Harness/>);
      await screen.findByText("This draft has no task schedule");
      fireEvent.click(screen.getByRole("checkbox"));
      fireEvent.click(screen.getByRole("button", { name: /generate tasks/i }));
      expect(await screen.findByRole("alert")).toHaveTextContent("Generation transaction rolled back");
      fireEvent.click(screen.getByRole("button", { name: /retry generation/i }));
      await waitFor(() => expect(projectsApi.generateTasks).toHaveBeenCalledTimes(2));
    });

    it("uses a full-width mobile action", async () => {
      render(<Harness/>);
      await screen.findByText("This draft has no task schedule");
      expect(screen.getByRole("button", { name: /generate tasks/i })).toHaveClass("w-full", "sm:w-auto");
    });

    it("tells a non-Admin that only Admin can prepare the schedule", async () => {
      render(<Harness role="project_manager"/>);
      expect(await screen.findByText(/Only Admin can prepare the task schedule/i)).toBeInTheDocument();
      expect(screen.queryByRole("button", { name: /generate tasks/i })).not.toBeInTheDocument();
    });
  });
});
