import { AlertTriangle, Save, ShieldAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Alert, Button, Field, Input, Modal, Select, Textarea } from "../../../components/ui";
import { APPROVED_PHASES, EXTERNAL_PARTIES, REQUIRED_BY_TYPES } from "./templateAuthoringOptions";

const emptyGate={code:"",approval_name:"",description:"",external_party:"",required_by_type:"pre_activation",required_by_value:"",impact:"",sequence_no:"",mapping_classification:"unmapped",broad_mapping_text:"",task_ids:[]};
function asForm(gate,nextSequence,suggestedCode){if(!gate)return{...emptyGate,sequence_no:nextSequence??"",code:suggestedCode??""};return{code:gate.code||"",approval_name:gate.approval_name||"",description:gate.description||"",external_party:gate.external_party||"",required_by_type:gate.required_by_type||"pre_activation",required_by_value:gate.required_by_value||"",impact:gate.impact||"",sequence_no:gate.sequence_no??nextSequence??"",mapping_classification:gate.mapping_classification||"unmapped",broad_mapping_text:gate.broad_mapping_text||"",task_ids:(gate.task_ids||gate.affected_tasks?.map(task=>task.id)||[]).map(String)}}
function message(error){const d=error?.details?.detail;if(d?.code==="stale_template_version")return"This draft changed in another session. Refresh before retrying.";return d?.message||error?.message||"The gate could not be saved.";}
export function TemplateGateEditorModal({gate,gates=[],tasks,durationDays,revisionToken,nextSequence,suggestedCode,onClose,onSaved,onDirtyChange}){
 const [form,setForm]=useState(()=>asForm(gate,nextSequence,suggestedCode));const [errors,setErrors]=useState({});const [requestError,setRequestError]=useState("");const [saving,setSaving]=useState(false);const initial=useMemo(()=>JSON.stringify(asForm(gate,nextSequence,suggestedCode)),[gate,nextSequence,suggestedCode]);const dirty=JSON.stringify(form)!==initial;
 const phaseOptions=useMemo(()=>Array.from(new Set([...APPROVED_PHASES,...tasks.map(item=>item.phase).filter(Boolean)])).sort(),[tasks]);
 useEffect(()=>{onDirtyChange?.(dirty);return()=>onDirtyChange?.(false)},[dirty,onDirtyChange]);
 function change(name,value){setForm(current=>{const next={...current,[name]:value};if(name==="required_by_type"&&value==="pre_activation")next.required_by_value="";return next});setErrors(current=>({...current,[name]:""}));setRequestError("");}
 function toggleTask(id){change("task_ids",form.task_ids.includes(id)?form.task_ids.filter(x=>x!==id):[...form.task_ids,id]);}
 function validate(){const e={};if(!form.code.trim())e.code="Code is required.";if(!form.approval_name.trim())e.approval_name="Approval name is required.";if(!Number.isInteger(Number(form.sequence_no))||Number(form.sequence_no)<1)e.sequence_no="Enter a positive sequence.";if(form.required_by_type!=="pre_activation"&&!String(form.required_by_value).trim())e.required_by_value="Select or enter the required-by value.";if(form.required_by_type==="project_day"&&(Number(form.required_by_value)<1||Number(form.required_by_value)>durationDays))e.required_by_value=`Use Day 1-${durationDays}.`;if(form.mapping_classification==="exact"&&!form.task_ids.length)e.task_ids="Select at least one explicit task.";if(form.mapping_classification==="broad_text"&&!form.broad_mapping_text.trim())e.broad_mapping_text="Preserve the original broad wording.";setErrors(e);return!Object.keys(e).length;}
 async function submit(event){event.preventDefault();if(saving||!validate())return;const old=gate?.mapping_classification;if(gate&&old!==form.mapping_classification){const copy=form.mapping_classification==="broad_text"?"Changing to broad text removes this gate's exact mapping rows. Tasks are not deleted. Continue?":form.mapping_classification==="exact"?"Changing to exact mapping keeps only the tasks you explicitly select. No tasks will be inferred. Continue?":"Changing to unmapped removes exact mapping rows and marks the gate as requiring configuration. Continue?";if(!window.confirm(copy))return;}setSaving(true);setRequestError("");try{await onSaved({code:form.code.trim(),approval_name:form.approval_name.trim(),description:form.description.trim()||null,external_party:form.external_party||null,required_by_type:form.required_by_type,required_by_value:form.required_by_type==="pre_activation"?null:String(form.required_by_value).trim()||null,impact:form.impact.trim()||null,sequence_no:Number(form.sequence_no),mapping_classification:form.mapping_classification,broad_mapping_text:form.mapping_classification==="broad_text"?form.broad_mapping_text.trim():null,task_ids:form.mapping_classification==="exact"?form.task_ids:[],revision_token:revisionToken},gate,initial)}catch(error){setRequestError(message(error));setSaving(false)}}
 function close(){if(!dirty||window.confirm("Discard unsaved gate changes?"))onClose();}
 function requiredValueControl(){if(form.required_by_type==="pre_activation")return <Input aria-label="Gate required by value" value="No additional value required" readOnly className="bg-slate-100"/>;if(form.required_by_type==="project_day")return <Input aria-label="Gate required by value" type="number" min="1" max={durationDays} value={form.required_by_value} onChange={e=>change("required_by_value",e.target.value)}/>;if(form.required_by_type==="before_task")return <Select aria-label="Gate required by value" value={form.required_by_value} onChange={e=>change("required_by_value",e.target.value)}><option value="">Select task</option>{tasks.map(task=><option key={task.id} value={task.code}>{task.code} — {task.title}</option>)}</Select>;if(form.required_by_type==="before_phase")return <Select aria-label="Gate required by value" value={form.required_by_value} onChange={e=>change("required_by_value",e.target.value)}><option value="">Select phase</option>{phaseOptions.map(value=><option key={value}>{value}</option>)}</Select>;return <Input aria-label="Gate required by value" value={form.required_by_value} onChange={e=>change("required_by_value",e.target.value)}/>;}
 return <Modal title={gate?"Edit draft external gate":"Add draft external gate"} subtitle="Mappings are explicit. Broad text never creates inferred task links." onClose={close} className="sm:max-w-4xl"><form className="grid gap-6" onSubmit={submit} noValidate>
 {requestError&&<Alert tone="danger" role="alert"><AlertTriangle size={18}/><div><strong>Gate was not saved</strong><span className="mt-1 block">{requestError}</span></div></Alert>}
 <section className="grid gap-4 sm:grid-cols-2"><Field label="Gate code" error={errors.code} hint="Suggested automatically; uniqueness is backend-validated."><Input aria-label="Gate code" value={form.code} onChange={e=>change("code",e.target.value)}/></Field><Field label="Sequence" error={errors.sequence_no} hint="Generated from the current gate order."><Input aria-label="Gate sequence number" type="number" min="1" value={form.sequence_no} readOnly className="bg-slate-100"/></Field><Field label="Approval / NOC / input" error={errors.approval_name} className="sm:col-span-2"><Input aria-label="Gate approval name" value={form.approval_name} onChange={e=>change("approval_name",e.target.value)}/></Field><Field label="Description" className="sm:col-span-2"><Textarea aria-label="Gate description" value={form.description} onChange={e=>change("description",e.target.value)}/></Field><Field label="External party"><Select aria-label="Gate external party" value={form.external_party} onChange={e=>change("external_party",e.target.value)}><option value="">Select external party</option>{EXTERNAL_PARTIES.map(value=><option key={value}>{value}</option>)}</Select></Field><Field label="Required-by type"><Select aria-label="Gate required by type" value={form.required_by_type} onChange={e=>change("required_by_type",e.target.value)}>{REQUIRED_BY_TYPES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></Field><Field label="Required-by value" error={errors.required_by_value} className="sm:col-span-2">{requiredValueControl()}</Field><Field label="Impact" className="sm:col-span-2"><Textarea aria-label="Gate impact" value={form.impact} onChange={e=>change("impact",e.target.value)}/></Field></section>
 <section className="grid gap-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div><strong className="text-sm text-amber-950">Mapping classification</strong><p className="mt-1 text-xs font-semibold leading-5 text-amber-800">Choose deliberately. Requires-configuration is calculated automatically.</p></div><Field label="Classification"><Select aria-label="Gate mapping classification" value={form.mapping_classification} onChange={e=>change("mapping_classification",e.target.value)}><option value="exact">Exact task mapping</option><option value="broad_text">Broad original text</option><option value="unmapped">Unmapped / requires configuration</option></Select></Field>
 {form.mapping_classification==="broad_text"&&<><Alert tone="warning"><ShieldAlert size={18}/><div><strong>Original wording is preserved</strong><span className="mt-1 block">No exact task rows will be created from this text.</span></div></Alert><Field label="Original broad mapping text" error={errors.broad_mapping_text}><Textarea aria-label="Broad mapping text" value={form.broad_mapping_text} onChange={e=>change("broad_mapping_text",e.target.value)}/></Field></>}
 {form.mapping_classification==="unmapped"&&<Alert tone="warning"><ShieldAlert size={18}/><div><strong>Requires configuration</strong><span className="mt-1 block">This gate will have no exact task mappings.</span></div></Alert>}
 {form.mapping_classification==="exact"&&<div><strong className="text-xs font-black text-slate-700">Explicit affected tasks</strong>{errors.task_ids&&<p className="mt-1 text-xs font-bold text-rose-700">{errors.task_ids}</p>}<div className="mt-3 grid max-h-72 gap-2 overflow-auto sm:grid-cols-2">{tasks.map(task=><label key={task.id} className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-3 text-sm"><input aria-label={`Map ${task.code}`} type="checkbox" checked={form.task_ids.includes(String(task.id))} onChange={()=>toggleTask(String(task.id))} className="mt-0.5 size-4 accent-blue-700"/><span><b className="font-mono text-xs text-blue-700">{task.code}</b><span className="block text-xs font-semibold text-slate-700">{task.title}</span></span></label>)}</div></div>}
 </section><footer className="sticky -bottom-4 -mx-4 flex flex-col-reverse gap-2 border-t border-slate-100 bg-white/95 px-4 py-4 backdrop-blur sm:-bottom-6 sm:-mx-6 sm:flex-row sm:justify-end sm:px-6"><Button variant="secondary" className="w-full sm:w-auto" onClick={close}>Cancel</Button><Button type="submit" loading={saving} className="w-full sm:w-auto"><Save size={17}/>{gate?"Save gate":"Add gate"}</Button></footer>
 </form></Modal>;
}
