import { AlertTriangle, Save } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Alert, Button, Field, Input, Modal, Select, Textarea } from "../../../components/ui";
import { APPROVED_CATEGORIES, APPROVED_PHASES } from "./templateAuthoringOptions";

const emptyTask = { code:"", sequence_no:"", title:"", description:"", schedule_classification:"execution", planned_start_day:"", planned_end_day:"", phase:"", category:"", applicability:"mandatory", task_class:"", task_kind:"", evidence_required:false, duration_days:"" };
const asForm = (task, nextSequence, suggestedCode) => task ? Object.fromEntries(Object.keys(emptyTask).map(key => [key, task[key] ?? (key === "evidence_required" ? false : "")])) : { ...emptyTask, sequence_no:nextSequence ?? "", code:suggestedCode ?? "" };
const optional = value => String(value ?? "").trim() || null;
function derivedDuration(form){ if(form.schedule_classification!=="execution") return form.duration_days; const start=Number(form.planned_start_day), end=Number(form.planned_end_day); return Number.isInteger(start)&&Number.isInteger(end)&&end>=start ? end-start+1 : ""; }
function errorCopy(error) { const detail=error?.details?.detail; if(detail?.code==="stale_template_version")return "This draft changed in another session. Refresh it before retrying."; return detail?.message||error?.message||"The task could not be saved."; }

export function TemplateTaskEditorModal({ task, tasks=[], durationDays, revisionToken, nextSequence, suggestedCode, onClose, onSaved, onDirtyChange }) {
  const [form,setForm]=useState(()=>asForm(task,nextSequence,suggestedCode)); const [errors,setErrors]=useState({}); const [requestError,setRequestError]=useState(""); const [saving,setSaving]=useState(false);
  const initial=useMemo(()=>JSON.stringify(asForm(task,nextSequence,suggestedCode)),[nextSequence,suggestedCode,task]); const dirty=JSON.stringify(form)!==initial;
  const phaseOptions=useMemo(()=>Array.from(new Set([...APPROVED_PHASES,...tasks.map(item=>item.phase).filter(Boolean)])).sort(),[tasks]);
  const categoryOptions=useMemo(()=>Array.from(new Set([...APPROVED_CATEGORIES,...tasks.map(item=>item.category).filter(Boolean)])).sort(),[tasks]);
  useEffect(()=>{onDirtyChange?.(dirty);return()=>onDirtyChange?.(false)},[dirty,onDirtyChange]);
  function change(name,value){setForm(current=>{const next={...current,[name]:value};if(name==="schedule_classification"&&value==="pre_activation"){next.planned_start_day="";next.planned_end_day="";}if(name==="planned_start_day"&&next.planned_end_day==="")next.planned_end_day=value;next.duration_days=derivedDuration(next);return next});setErrors(current=>({...current,[name]:""}));setRequestError("");}
  function validate(){const next={};const sequence=Number(form.sequence_no),start=form.planned_start_day===""?null:Number(form.planned_start_day),end=form.planned_end_day===""?null:Number(form.planned_end_day);if(!form.code.trim())next.code="Task code is required.";if(!form.title.trim())next.title="Task title is required.";if(!Number.isInteger(sequence)||sequence<1)next.sequence_no="Enter a positive sequence.";if(form.schedule_classification==="execution"){if(!Number.isInteger(start))next.planned_start_day="Execution tasks need a start day.";if(!Number.isInteger(end))next.planned_end_day="Execution tasks need an end day.";if(Number.isInteger(start)&&(start<1||start>durationDays))next.planned_start_day=`Use Day 1-${durationDays}.`;if(Number.isInteger(end)&&(end<1||end>durationDays))next.planned_end_day=`Use Day 1-${durationDays}.`;if(Number.isInteger(start)&&Number.isInteger(end)&&start>end)next.planned_end_day="End day cannot precede start day.";}setErrors(next);return !Object.keys(next).length;}
  async function submit(event){event.preventDefault();if(saving||!validate())return;setSaving(true);setRequestError("");const pre=form.schedule_classification==="pre_activation";const duration=pre?(form.duration_days===""?null:Number(form.duration_days)):Number(derivedDuration(form));try{await onSaved({code:form.code.trim(),sequence_no:Number(form.sequence_no),title:form.title.trim(),description:optional(form.description),schedule_classification:form.schedule_classification,planned_start_day:pre?null:Number(form.planned_start_day),planned_end_day:pre?null:Number(form.planned_end_day),phase:optional(form.phase),category:optional(form.category),applicability:form.applicability,task_class:optional(form.task_class),task_kind:optional(form.task_kind),evidence_required:Boolean(form.evidence_required),duration_days:Number.isInteger(duration)?duration:null,revision_token:revisionToken},task)}catch(error){setRequestError(errorCopy(error));setSaving(false)}}
  function close(){if(!dirty||window.confirm("Discard unsaved task changes?"))onClose();}
  return <Modal title={task?"Edit draft task":"Add draft task"} subtitle="Codes and sequence are suggested; persisted values remain backend-validated." onClose={close} className="sm:max-w-4xl"><form className="grid gap-6" onSubmit={submit} noValidate>
    {requestError&&<Alert tone="danger" role="alert"><AlertTriangle size={18}/><div><strong>Task was not saved</strong><span className="mt-1 block">{requestError}</span></div></Alert>}
    <section className="grid gap-4 sm:grid-cols-2"><Field label="Task code" error={errors.code} hint="Suggested automatically; uniqueness is checked by the backend."><Input aria-label="Task code" value={form.code} onChange={e=>change("code",e.target.value)} /></Field><Field label="Sequence number" error={errors.sequence_no} hint="Generated from the current draft order."><Input aria-label="Sequence number" type="number" min="1" value={form.sequence_no} readOnly className="bg-slate-100"/></Field><Field label="Task title" error={errors.title} className="sm:col-span-2"><Input aria-label="Task title" value={form.title} onChange={e=>change("title",e.target.value)}/></Field><Field label="Description" className="sm:col-span-2"><Textarea aria-label="Task description" value={form.description} onChange={e=>change("description",e.target.value)}/></Field></section>
    <section className="rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:p-5"><h3 className="font-black text-slate-950">Schedule</h3><div className="mt-4 grid gap-4 sm:grid-cols-3"><Field label="Schedule classification"><Select aria-label="Schedule classification" value={form.schedule_classification} onChange={e=>change("schedule_classification",e.target.value)}><option value="pre_activation">Pre-Activation</option><option value="execution">Execution</option></Select></Field><Field label="Planned start day" error={errors.planned_start_day}><Input aria-label="Planned start day" type="number" min="1" max={durationDays} disabled={form.schedule_classification==="pre_activation"} value={form.planned_start_day} onChange={e=>change("planned_start_day",e.target.value)}/></Field><Field label="Planned end day" error={errors.planned_end_day}><Input aria-label="Planned end day" type="number" min="1" max={durationDays} disabled={form.schedule_classification==="pre_activation"} value={form.planned_end_day} onChange={e=>change("planned_end_day",e.target.value)}/></Field><Field label="Task duration" hint={form.schedule_classification==="execution"?"Calculated automatically from start and end day.":"Optional for Pre-Activation only."}><Input aria-label="Task duration" type="number" min="1" value={form.duration_days} readOnly={form.schedule_classification==="execution"} onChange={e=>change("duration_days",e.target.value)} className={form.schedule_classification==="execution"?"bg-slate-100":""}/></Field><Field label="Phase"><Select aria-label="Task phase" value={form.phase} onChange={e=>change("phase",e.target.value)}><option value="">Select phase</option>{phaseOptions.map(value=><option key={value}>{value}</option>)}</Select></Field><Field label="Category"><Select aria-label="Task category" value={form.category} onChange={e=>change("category",e.target.value)}><option value="">Select category</option>{categoryOptions.map(value=><option key={value}>{value}</option>)}</Select></Field></div></section>
    <section className="grid gap-4 sm:grid-cols-2"><Field label="Applicability"><Select aria-label="Task applicability" value={form.applicability} onChange={e=>change("applicability",e.target.value)}><option value="mandatory">Mandatory</option><option value="conditional">Conditional</option></Select></Field><Field label="Task class" hint="No approved class master is configured in Phase 2."><Input aria-label="Task class" value={form.task_class} readOnly className="bg-slate-100"/></Field><Field label="Task kind" hint="No approved kind master is configured in Phase 2."><Input aria-label="Task kind" value={form.task_kind} readOnly className="bg-slate-100"/></Field><label className="flex min-h-11 items-center gap-3 self-end rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700 shadow-sm"><input aria-label="Evidence required" type="checkbox" checked={form.evidence_required} onChange={e=>change("evidence_required",e.target.checked)} className="size-4 accent-blue-700"/> Evidence required</label></section>
    <footer className="sticky -bottom-4 -mx-4 flex flex-col-reverse gap-2 border-t border-slate-100 bg-white/95 px-4 py-4 backdrop-blur sm:-bottom-6 sm:-mx-6 sm:flex-row sm:justify-end sm:px-6"><Button variant="secondary" className="w-full sm:w-auto" onClick={close}>Cancel</Button><Button type="submit" loading={saving} className="w-full sm:w-auto"><Save size={17}/>{task?"Save task":"Add task"}</Button></footer>
  </form></Modal>;
}
