"""fresh execution v2 workflow"""
from alembic import op
import sqlalchemy as sa
revision = "0006_execution_v2"
down_revision = "0005_workflow_permissions"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("users", sa.Column("phone", sa.Text()))
    op.execute("insert into role_module_permissions (id, role, module_key, can_view) select gen_random_uuid(), role_name, 'execution', true from (values ('admin'), ('project_manager'), ('supervisor')) roles(role_name) on conflict (role, module_key) do update set can_view = true")
    op.create_table("execution_templates", sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("name",sa.Text(),nullable=False),sa.Column("project_type",sa.Text(),nullable=False),sa.Column("duration_days",sa.Integer(),nullable=False,server_default="3"),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.text("true")),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.text("now()")))
    op.create_table("execution_template_tasks",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("template_id",sa.Uuid(),sa.ForeignKey("execution_templates.id",ondelete="CASCADE"),nullable=False),sa.Column("day_no",sa.Integer(),nullable=False),sa.Column("title",sa.Text(),nullable=False),sa.Column("category",sa.Text(),nullable=False,server_default="General"),sa.Column("priority",sa.Text(),nullable=False,server_default="medium"),sa.Column("instructions",sa.Text()),sa.Column("sort_order",sa.Integer(),nullable=False,server_default="1"))
    op.create_table("execution_projects",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("name",sa.Text(),nullable=False),sa.Column("client_name",sa.Text(),nullable=False),sa.Column("location",sa.Text(),nullable=False),sa.Column("project_type",sa.Text(),nullable=False),sa.Column("area",sa.Text()),sa.Column("start_date",sa.Date(),nullable=False),sa.Column("duration_days",sa.Integer(),nullable=False,server_default="3"),sa.Column("project_manager_id",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("supervisor_id",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("template_id",sa.Uuid(),sa.ForeignKey("execution_templates.id")),sa.Column("status",sa.Text(),nullable=False,server_default="active"),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.text("now()")))
    op.create_table("execution_days",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("project_id",sa.Uuid(),sa.ForeignKey("execution_projects.id",ondelete="CASCADE"),nullable=False),sa.Column("day_no",sa.Integer(),nullable=False),sa.Column("scheduled_date",sa.Date(),nullable=False),sa.UniqueConstraint("project_id","day_no",name="uq_execution_project_day"))
    op.create_table("execution_project_contractors",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("project_id",sa.Uuid(),sa.ForeignKey("execution_projects.id",ondelete="CASCADE"),nullable=False),sa.Column("contractor_id",sa.Uuid(),sa.ForeignKey("vendors.id",ondelete="CASCADE"),nullable=False),sa.Column("scope",sa.Text()),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.text("now()")),sa.UniqueConstraint("project_id","contractor_id",name="uq_execution_project_contractor"))
    op.create_table("execution_tasks",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("project_id",sa.Uuid(),sa.ForeignKey("execution_projects.id",ondelete="CASCADE"),nullable=False),sa.Column("day_id",sa.Uuid(),sa.ForeignKey("execution_days.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.Text(),nullable=False),sa.Column("category",sa.Text(),nullable=False,server_default="General"),sa.Column("instructions",sa.Text()),sa.Column("assigned_supervisor_id",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("assigned_contractor_id",sa.Uuid(),sa.ForeignKey("vendors.id")),sa.Column("assigned_subcontractor_id",sa.Uuid(),sa.ForeignKey("vendors.id")),sa.Column("priority",sa.Text(),nullable=False,server_default="medium"),sa.Column("status",sa.Text(),nullable=False,server_default="assigned"),sa.Column("proof_url",sa.Text()),sa.Column("remarks",sa.Text()),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.text("now()")),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.text("now()")))
    op.add_column("communication_logs", sa.Column("execution_project_id", sa.Uuid(), sa.ForeignKey("execution_projects.id", ondelete="CASCADE")))
    op.create_table("notification_outbox",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("task_id",sa.Uuid(),sa.ForeignKey("execution_tasks.id",ondelete="CASCADE"),nullable=False),sa.Column("recipient_type",sa.Text(),nullable=False),sa.Column("recipient_name",sa.Text(),nullable=False),sa.Column("phone",sa.Text()),sa.Column("message_preview",sa.Text(),nullable=False),sa.Column("status",sa.Text(),nullable=False,server_default="preview"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.text("now()")))


def downgrade():
    op.drop_table("notification_outbox"); op.drop_column("communication_logs","execution_project_id"); op.drop_table("execution_tasks"); op.drop_table("execution_project_contractors"); op.drop_table("execution_days"); op.drop_table("execution_projects"); op.drop_table("execution_template_tasks"); op.drop_table("execution_templates"); op.drop_column("users","phone")