import { Plus } from "lucide-react";
import { useMemo, useState } from "react";
import { projectsApi } from "../../../api/projectsApi";
import { Button, Field, Input, Modal, Pill, Select, Textarea } from "../../../components/ui";

const initialForm = { title: "", phase: "", category: "", planned_start_day: "", planned_end_day: "", reason: "" };

function apiMessage(error) {
  return error?.message || "The project-specific task could not be created.";
}

export function ProjectManualTaskModal({ projectId, onClose, onCreated, phaseOptions = [], categoriesByPhase = {} }) {
  const [form, setForm] = useState(initialForm);
  const [errors, setErrors] = useState({});
  const [apiError, setApiError] = useState("");
  const [saving, setSaving] = useState(false);
  const duration = useMemo(() => {
    const start = Number(form.planned_start_day);
    const end = Number(form.planned_end_day);
    return Number.isInteger(start) && Number.isInteger(end) && start > 0 && end >= start ? end - start + 1 : null;
  }, [form.planned_end_day, form.planned_start_day]);

  function update(field, value) {
    setForm(current => {
      if (field === "phase") return { ...current, phase: value, category: "" };
      return { ...current, [field]: value };
    });
    setErrors(current => ({ ...current, [field]: "", ...(field === "phase" ? { category: "" } : {}) }));
  }
  const categoryOptions = categoriesByPhase[form.phase] || [];
  function validate() {
    const next = {};
    ["title", "phase", "category", "reason"].forEach(field => { if (!form[field].trim()) next[field] = "Required."; });
    const start = Number(form.planned_start_day);
    const end = Number(form.planned_end_day);
    if (!Number.isInteger(start) || start < 1) next.planned_start_day = "Enter a valid start day.";
    if (!Number.isInteger(end) || end < 1) next.planned_end_day = "Enter a valid end day.";
    if (!next.planned_start_day && !next.planned_end_day && start > end) next.planned_end_day = "End day must be on or after start day.";
    setErrors(next);
    return Object.keys(next).length === 0;
  }

  async function submit(event) {
    event.preventDefault();
    if (saving || !validate()) return;
    setSaving(true); setApiError("");
    try {
      const created = await projectsApi.createManualTask(projectId, {
        title: form.title.trim(), phase: form.phase.trim(), category: form.category.trim(),
        planned_start_day: Number(form.planned_start_day), planned_end_day: Number(form.planned_end_day), reason: form.reason.trim(),
      });
      onCreated?.(created);
      onClose();
    } catch (error) { setApiError(apiMessage(error)); } finally { setSaving(false); }
  }

  return <Modal title="Add project-specific task" subtitle="Create a manual task for this draft project only. The published template is not changed." onClose={() => { if (!saving) onClose(); }} className="sm:max-w-2xl">
    <form className="grid gap-5" onSubmit={submit}>
      <div className="flex items-center justify-between gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4"><div><p className="text-sm font-black text-blue-950">Project-only scope</p><p className="mt-1 text-xs leading-5 text-blue-700">A unique MANUAL code and final sequence are generated by the backend.</p></div><Pill tone="blue">Manual source</Pill></div>
      <Field label="Title" htmlFor="manual-task-title" error={errors.title}><Input id="manual-task-title" value={form.title} onChange={e => update("title", e.target.value)} maxLength={500} disabled={saving}/></Field>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Phase" htmlFor="manual-task-phase" error={errors.phase}><Select id="manual-task-phase" value={form.phase} onChange={e => update("phase", e.target.value)} disabled={saving || !phaseOptions.length}><option value="">{phaseOptions.length ? "Select phase" : "No project phases available"}</option>{phaseOptions.map(option => <option key={option} value={option}>{option}</option>)}</Select></Field><Field label="Category" htmlFor="manual-task-category" error={errors.category}><Select id="manual-task-category" value={form.category} onChange={e => update("category", e.target.value)} disabled={saving || !form.phase || !categoryOptions.length}><option value="">{!form.phase ? "Select phase first" : categoryOptions.length ? "Select category" : "No categories available"}</option>{categoryOptions.map(option => <option key={option} value={option}>{option}</option>)}</Select></Field></div>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Start day" htmlFor="manual-task-start" error={errors.planned_start_day}><Input id="manual-task-start" type="number" min="1" value={form.planned_start_day} onChange={e => update("planned_start_day", e.target.value)} disabled={saving}/></Field><Field label="End day" htmlFor="manual-task-end" error={errors.planned_end_day} hint={duration ? `${duration} day${duration === 1 ? "" : "s"}` : undefined}><Input id="manual-task-end" type="number" min="1" value={form.planned_end_day} onChange={e => update("planned_end_day", e.target.value)} disabled={saving}/></Field></div>
      <Field label="Reason" htmlFor="manual-task-reason" error={errors.reason}><Textarea id="manual-task-reason" value={form.reason} onChange={e => update("reason", e.target.value)} maxLength={2000} placeholder="Why is this project-specific task required?" disabled={saving}/></Field>
      {apiError && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{apiError}</div>}
      <div className="grid gap-2 sm:grid-cols-2"><Button type="button" variant="secondary" disabled={saving} onClick={onClose}>Cancel</Button><Button type="submit" loading={saving} disabled={saving}><Plus size={16}/> Add manual task</Button></div>
    </form>
  </Modal>;
}
