import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { templatesApi } from "../../api/templatesApi";
import { TemplateDraftEditorEntry } from "./components/TemplateDraftEditorEntry";

vi.mock("../../api/templatesApi",()=>({templatesApi:{getVersion:vi.fn(),listTasks:vi.fn(),listDependencies:vi.fn(),listGates:vi.fn(),createGate:vi.fn(),updateGate:vi.fn(),configureGateMappings:vi.fn(),deleteGate:vi.fn(),validateVersion:vi.fn(),publishVersion:vi.fn(),createTask:vi.fn(),updateTask:vi.fn(),deleteTask:vi.fn(),reorderTasks:vi.fn(),createDependency:vi.fn(),updateDependency:vi.fn(),deleteDependency:vi.fn()}}));
const summary={version_id:"draft-1",template_code:"TEST",template_name:"Test",version_no:2,status:"draft",duration_days:45,updated_at:"2026-07-28T10:00:00Z",revision_token:"rev-1"};
const tasks=[{id:"task-1",code:"T001",title:"Confirm site",sequence_no:1},{id:"task-2",code:"T002",title:"Start work",sequence_no:2}];
const broad={id:"gate-1",code:"E001",approval_name:"General approval",description:null,external_party:"Client",required_by_type:"source_text",required_by_value:"Before work",impact:"Blocks work",sequence_no:1,mapping_classification:"broad_text",broad_mapping_text:"Affected activities",requires_configuration:true,affected_tasks:[]};
const page=items=>({items,pagination:{page:1,page_size:100,total:items.length,total_pages:items.length?1:0},summary:{total:0}});
function view(role="super_admin",s=summary){return render(<TemplateDraftEditorEntry summary={s} user={{role}} onBack={vi.fn()}/>)}
beforeEach(()=>{vi.clearAllMocks();templatesApi.getVersion.mockResolvedValue(summary);templatesApi.listTasks.mockResolvedValue(page(tasks));templatesApi.listDependencies.mockResolvedValue(page([]));templatesApi.listGates.mockResolvedValue(page([broad]));templatesApi.createGate.mockResolvedValue({gate:broad,revision_token:"rev-2"});templatesApi.updateGate.mockResolvedValue({gate:broad,revision_token:"rev-2"});templatesApi.configureGateMappings.mockResolvedValue({gate:{...broad,mapping_classification:"exact",affected_tasks:[tasks[0]]},revision_token:"rev-3"});templatesApi.deleteGate.mockResolvedValue({gate_id:"gate-1",deleted:true,revision_token:"rev-2"});});
async function openGates(){view();await screen.findByTestId("draft-task-T001");fireEvent.click(screen.getByRole("button",{name:/external gates/i}));return screen.findByTestId("draft-gate-gate-1");}
describe("draft gate authoring",()=>{
 it("creates an exact gate using only explicit task selection",async()=>{await openGates();fireEvent.click(screen.getByRole("button",{name:/add gate/i}));const d=screen.getByRole("dialog",{name:/add draft external gate/i});fireEvent.change(within(d).getByLabelText("Gate code"),{target:{value:"E002"}});fireEvent.change(within(d).getByLabelText("Gate approval name"),{target:{value:"Core cutting approval"}});fireEvent.change(within(d).getByLabelText("Gate sequence number"),{target:{value:"2"}});fireEvent.change(within(d).getByLabelText("Gate mapping classification"),{target:{value:"exact"}});fireEvent.click(within(d).getByLabelText("Map T001"));fireEvent.click(within(d).getByRole("button",{name:/add gate/i}));await waitFor(()=>expect(templatesApi.createGate).toHaveBeenCalledWith("draft-1",expect.objectContaining({mapping_classification:"exact",task_ids:["task-1"],broad_mapping_text:null,revision_token:"rev-1"})));});
 it("preserves broad text and never infers links",async()=>{await openGates();expect(screen.getByTestId("draft-gate-gate-1")).toHaveTextContent("Affected activities");expect(screen.getByTestId("draft-gate-gate-1")).toHaveTextContent("No exact links inferred");fireEvent.click(screen.getAllByRole("button",{name:/edit gate E001/i})[0]);const d=screen.getByRole("dialog",{name:/edit draft external gate/i});expect(within(d).getByLabelText("Broad mapping text")).toHaveValue("Affected activities");expect(within(d).queryByLabelText("Map T001")).not.toBeInTheDocument();});
 it("confirms classification transition and explains exact-to-broad effect",async()=>{vi.spyOn(window,"confirm").mockReturnValue(false);await openGates();fireEvent.click(screen.getAllByRole("button",{name:/edit gate E001/i})[0]);const d=screen.getByRole("dialog",{name:/edit draft external gate/i});fireEvent.change(within(d).getByLabelText("Gate mapping classification"),{target:{value:"exact"}});fireEvent.click(within(d).getByLabelText("Map T001"));fireEvent.click(within(d).getByRole("button",{name:/save gate/i}));expect(window.confirm).toHaveBeenCalledWith(expect.stringMatching(/No tasks will be inferred/i));expect(templatesApi.configureGateMappings).not.toHaveBeenCalled();});
 it("deletes only the gate through the gate endpoint",async()=>{await openGates();fireEvent.click(screen.getAllByRole("button",{name:/delete gate E001/i})[0]);const d=screen.getByRole("dialog",{name:/delete E001/i});expect(within(d).getByText(/Tasks are not deleted/i)).toBeInTheDocument();fireEvent.click(within(d).getByRole("button",{name:/^delete gate$/i}));await waitFor(()=>expect(templatesApi.deleteGate).toHaveBeenCalledWith("draft-1","gate-1","rev-1"));});
 it("shows stale errors and keeps published/non-super-admin immutable",async()=>{templatesApi.createGate.mockRejectedValue({details:{detail:{code:"stale_template_version"}}});await openGates();fireEvent.click(screen.getByRole("button",{name:/add gate/i}));const d=screen.getByRole("dialog",{name:/add draft external gate/i});fireEvent.change(within(d).getByLabelText("Gate code"),{target:{value:"E002"}});fireEvent.change(within(d).getByLabelText("Gate approval name"),{target:{value:"Approval"}});fireEvent.change(within(d).getByLabelText("Gate sequence number"),{target:{value:"2"}});fireEvent.click(within(d).getByRole("button",{name:/add gate/i}));expect(await within(d).findByText(/changed in another session/i)).toBeInTheDocument();cleanup();view("admin");expect(await screen.findByText("Draft authoring is unavailable")).toBeInTheDocument();cleanup();const published={...summary,status:"published"};templatesApi.getVersion.mockResolvedValue(published);view("super_admin",published);expect(await screen.findByText("Draft authoring is unavailable")).toBeInTheDocument();});
 it("uses full-width mobile actions",async()=>{await openGates();expect(screen.getByRole("button",{name:/add gate/i})).toHaveClass("w-full");fireEvent.click(screen.getByRole("button",{name:/add gate/i}));expect(within(screen.getByRole("dialog")).getByRole("button",{name:/add gate/i})).toHaveClass("w-full");});
});
