import { useState } from "react";
import { authApi } from "../../api/authApi";
import { Card } from "../../components/ui";

export function SecurityPage({ action }) {
  const [token, setToken] = useState("");
  async function change(e) { e.preventDefault(); await action(() => authApi.changePassword(Object.fromEntries(new FormData(e.currentTarget))), "Password changed"); e.currentTarget.reset(); }
  async function forgot(e) { e.preventDefault(); const res = await authApi.requestReset(Object.fromEntries(new FormData(e.currentTarget))); setToken(res.token || res.message); }
  return <div className="stack grid gap-5"><Card><div className="panel-title mb-4 flex items-start justify-between gap-4 [&_p]:m-0 [&_p]:text-xs [&_p]:font-black [&_p]:uppercase [&_p]:tracking-[0.18em] [&_p]:text-blue-700 [&_h2]:m-0 [&_h2]:text-2xl [&_h2]:font-black"><div><p>Security</p><h2>Change password</h2></div></div><form className="smart-form grid grid-cols-2 gap-3 max-[620px]:grid-cols-1 [&_input]:min-h-12 [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-200 [&_input]:px-4 [&_button]:col-span-full [&_button]:min-h-12 [&_button]:rounded-xl [&_button]:bg-blue-700 [&_button]:font-black [&_button]:text-white max-[620px]:[&_button]:col-span-1" onSubmit={change}><input name="current_password" type="password" placeholder="Current password" /><input name="new_password" type="password" placeholder="New password" /><button>Change password</button></form></Card><Card><div className="panel-title mb-4 flex items-start justify-between gap-4 [&_p]:m-0 [&_p]:text-xs [&_p]:font-black [&_p]:uppercase [&_p]:tracking-[0.18em] [&_p]:text-blue-700 [&_h2]:m-0 [&_h2]:text-2xl [&_h2]:font-black"><div><p>Local reset</p><h2>Forgot password token</h2></div></div><form className="smart-form grid grid-cols-2 gap-3 max-[620px]:grid-cols-1 [&_input]:min-h-12 [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-200 [&_input]:px-4 [&_button]:col-span-full [&_button]:min-h-12 [&_button]:rounded-xl [&_button]:bg-blue-700 [&_button]:font-black [&_button]:text-white max-[620px]:[&_button]:col-span-1" onSubmit={forgot}><input name="email" placeholder="Email" /><button>Create token</button></form>{token && <div className="token-box mt-4 flex items-center gap-3 overflow-x-auto rounded-2xl bg-slate-100 p-4 [&_code]:min-w-0 [&_code]:flex-1 [&_button]:rounded-xl [&_button]:bg-blue-700 [&_button]:px-4 [&_button]:py-2 [&_button]:font-black [&_button]:text-white"><code>{token}</code><button onClick={() => navigator.clipboard?.writeText(token)}>Copy token</button></div>}</Card></div>;
}
